<?php

/**
*
* Article
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Article extends Entity {
    public $idUser;     // int(11)
    public $idCategorie;     // int(11)
    public $titre;     // varchar(80)
    public $contenu;     // text
    public $image;     // varchar(255)
    public $date;     // datetime

    public function __construct(
        $idUser = "",
        $idCategorie = "",
        $titre = "",
        $contenu = "",
        $image = "",
        $date = "",
    $id = false) {
        parent::__construct($id);

        $this->idUser = $idUser;
        $this->idCategorie = $idCategorie;
        $this->titre = $titre;
        $this->contenu = $contenu;
        $this->image = $image;
        $this->date = $date;
    }
}
?>
