<?php

/**
 *
 * Commentaire
 *
 * This class was generated by a script. Please be careful changing it.
 * Regenerate it will erase all changes!
 */

namespace App\Models\Tables;

use App\Models\Queries\UserSQL;
use App\Modules\User\User;
use Helpers\DB\Entity;


class Commentaire extends Entity
{

    public $id_article;     // int(11)
    public $id_user;     // int(11)
    public $contenu;     // text
    public $date;     // datetime

    public function __construct(
        $idArticle = "",
        $idUser = "",
        $contenu = "",
        $date = "",
        $id = false)
    {
        parent::__construct($id);

        $this->id_article = $idArticle;
        $this->id_user = $idUser;
        $this->contenu = $contenu;
        $this->date = $date;
    }

    function getUsername(){
        $model_user = new UserSQL();
        $user = $model_user->findById($this->id_user);

        return $user->login;
    }
}

?>
