<?php

/**
*
* Commentaire
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Commentaire extends Entity {
    public $id_article;     // int(11)
    public $id_user;     // int(11)
    public $contenu;     // text
    public $date;     // datetime

    public function __construct(
        $id_article = "",
        $id_user = "",
        $contenu = "",
        $date = "",
    $id = false) {
        parent::__construct($id);

        $this->idArticle = $id_article;
        $this->idUser = $id_user;
        $this->contenu = $contenu;
        $this->date = $date;
    }
}
?>
