<?php

/**
*
* Commentaire
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Commentaire extends Entity {
    public $idArticle;     // int(11)
    public $idUser;     // int(11)
    public $contenu;     // text
    public $date;     // datetime

    public function __construct(
        $idArticle = "",
        $idUser = "",
        $contenu = "",
        $date = "",
    $id = false) {
        parent::__construct($id);

        $this->idArticle = $idArticle;
        $this->idUser = $idUser;
        $this->contenu = $contenu;
        $this->date = $date;
    }
}
?>
