user:
  login: varchar(255)
  email: varchar(255)
  password: varchar(255)
  cookie: varchar(255)
  admin: int(1)
  
categorie: 
  titre: varchar(80) 
  
article:
  id_user: int(11)
  id_categorie: int(11)
  titre: varchar(80)
  contenu: text
  image: varchar(255)
  date: datetime 
    
commentaire:
    id_article: int(11)
    id_user: int(11)
    contenu: text
    date: datetime 